coverage:
  notify:
    webhook:
      default:
        url: "hhttps://codecov2discord.herokuapp.com/discord-webhook/333327638238330880/Oh7Eu5mnnh96p1U-LvJOBSeDTkQ6HebS0VJj0h6f2uUUFWPqR0xY_Rw5EP3TwLwISdX4"